[build]
  command = "hugo"
  publish = "public"

[context.production.environment]
  HUGO_VERSION = "0.111.3"

[context.production]
  command = "hugo"
  publish = "public"
  branch = "main"

[context.dev]
  command = "hugo"
  publish = "public"
  branch = "dev"