backend:
  name: git-gateway
  repo: wearebolean/hugo-decap-template
  branch: main

media_folder: "static/images"
public_folder: "images"

site_url: https://hugo-decap-template.netlify.app/
logo_url: https://hugo-decap-template.netlify.app/images/logo.svg

i18n:
  structure: "multiple_files"
  locales:
    - "fr"
    - "en"

collections: 
  - label: "Carrieres"
    name: "carrieres"
    folder: "content/carrieres/list"
    create: true
    slug: "_{{slug}}/index"
    i18n: true
    editor:
      preview: false
    fields:
      - label: "Title"
        name: "title"
        hint: "Le nom unique du dossier qui contiendra toutes les infos ci-bas. Ex: nom-separer-par-des-traits"
        widget: "string"
      - label: "Affiché sur le site?"
        name: "type"
        widget: "select"
        i18n: duplicate
        options:
          - { label: "Oui", value: "visible" }
          - { label: "Non", value: "false" }
  - name: "global"
    label: "Global"
    files:
      - file: "config/_default/params.toml"
        label: "Contact Parameters"
        name: "params"
        fields:
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Phone", name: "phone", widget: "string" }
          - { label: "Phone link", name: "phone_link", widget: "string", hint: "Same as above but without spaces or special characters. Ex: 15143334444" }
          - { label: "Address", name: "address", widget: "string" }
          - { label: "Google Map link", name: "gmap_link", widget: "string" }