backend:
  name: git-gateway
  repo: wearebolean/hugo-decap-template
  branch: main

media_folder: "static/img" # Folder where user uploaded files should go
public_folder: "img"

i18n:
  structure: "multiple_files"
  locales:
    - "fr"
    - "en"

collections: 
  - label: Carrieres
    name: "carrieres"
    folder: "content/carrieres/cms-jobs"
    create: true
    slug: "_{{slug}}/index"
    i18n: true
    editor:
      preview: false
    fields:
      - label: "Title"
        name: "title"
        hint: "Le nom unique du dossier qui contiendra toutes les infos ci-bas. Ex: nom-separer-par-des-traits"
        widget: "string"
      - label: "Affiché sur le site?"
        name: "visible"
        widget: "select"
        i18n: duplicate
        options:
          - { label: "Oui", value: "true" }
          - { label: "Non", value: "false" }
      - label: "Sitemap"
        name: "sitemap"
        widget: "hidden"
        default: "true"
        i18n: duplicate
      - label: "Render as"
        name: "render_as"
        widget: "hidden"
        default: "cms-jobs"
        i18n: duplicate
      - label: "Titre de l'emploi"
        name: "job_title"
        widget: "string"
        i18n: true
      - label: "Emplacement"
        name: "area"
        widget: "string"
        i18n: duplicate
      - label: "Ton quotidien"
        name: "quotidien"
        widget: "list"
        fields: 
          - {label: "Ajouter", name: "line", widget: "string"}
        i18n: true
      - label: "C’est l’emploi idéal pour toi si"
        name: "ideal"
        widget: "list"
        fields: 
          - {label: "Ajouter", name: "line", widget: "string"}
        i18n: true
      - label: "Ce que nous t’offrons"
        name: "offrons"
        widget: "list"
        fields: 
          - {label: "Ajouter", name: "line", widget: "string"}
        i18n: true
      - label: "Requis"
        name: "requis"
        widget: "list"
        fields: 
          - {label: "Ajouter", name: "line", widget: "string"}
        i18n: true
  - name: "post" # Used in routes, ie.: /admin/collections/:slug/edit
    label: "Post" # Used in the UI, ie.: "New Post"
    folder: "content/post" # The path to the folder where the documents are stored
    create: true # Allow users to create new documents in this collection
    editor:
      preview: false
    fields: # The fields each document in this collection have
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Publish Date", name: "date", widget: "datetime"}
      - {label: "Intro Blurb", name: "description", widget: "text"}
      - {label: "Image", name: "image", widget: "image", required: false}
      - {label: "Body", name: "body", widget: "markdown"}
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/_index"
        label: "Home Page"
        name: "home"
        i18n: true
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: "Blurb", name: blurb, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Intro", name: intro, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Products", name: products, widget: list, fields: [
              {label: "Image", name: "image", widget: "image"},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Values", name: "values", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
      - file: "content/contact/_index"
        label: "Contact Page"
        name: "contact"
        i18n: true
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Logo, name: logo, widget: image}
          - {label: Body, name: body, widget: markdown}
          - label: Contact Entries
            name: contact_entries
            widget: list
            fields:
              - label: Heading
                name: heading
                widget: string
              - label: Text
                name: text
                widget: text

