backend:
  name: git-gateway
  repo: wearebolean/hugo-decap-template
  branch: main

media_folder: "static/images"
public_folder: "images"

site_url: https://hugo-decap-template.netlify.app/
logo_url: https://hugo-decap-template.netlify.app/images/logo.svg

i18n:
  structure: "multiple_files"
  locales:
    - "fr"
    - "en"

collections: 
  - label: "Carrieres"
    name: "carrieres"
    folder: "content/carrieres/list"
    create: true
    nested:
      depth: 100
    path: "_{{slug}}/index"
    media_folder: "uploads"
    public_folder: "uploads"
    i18n: true
    editor:
      preview: false
    fields:
      - label: "Title"
        name: "title"
        hint: "Le nom unique du dossier qui contiendra toutes les infos ci-bas. Ex: nom-separer-par-des-traits"
        widget: "string"
      - label: "Affiché sur le site?"
        name: "type"
        widget: "select"
        i18n: duplicate
        options:
          - { label: "Oui", value: "visible" }
          - { label: "Non", value: "false" }
      - label: "Sitemap"
        name: "sitemap"
        widget: "hidden"
        default: "true"
        i18n: duplicate
      - label: "Render as"
        name: "render_as"
        widget: "hidden"
        default: "cms-jobs"
        i18n: duplicate
      - label: "Content"
        name: "body"
        widget: "hidden"
        i18n: duplicate
        default: '{{< render-shared "carrieres/_introduction" >}}'
      - label: "Job Title"
        name: "job_title"
        widget: "string"
        i18n: true
      - label: "Emplacement"
        name: "area"
        widget: "string"
        i18n: duplicate
      - label: "Ton quotidien"
        name: "quotidien"
        widget: "list"
        fields:
          - {label: "Ajouter", name: "line", widget: "string"}
        i18n: true
      - label: "C’est l’emploi idéal pour toi si"
        name: "ideal"
        widget: "list"
        fields:
          - {label: "Ajouter", name: "line", widget: "string"}
        i18n: true
      - label: "Ce que nous t’offrons"
        name: "offrons"
        widget: "list"
        fields:
          - {label: "Ajouter", name: "line", widget: "string"}
        i18n: true
      - label: "Requis"
        name: "requis"
        widget: "list"
        fields:
          - {label: "Ajouter", name: "line", widget: "string"}
        i18n: true
  - name: "global"
    label: "Global"
    files:
      - file: "data/contact_params.toml"
        label: "Contact Infos"
        name: "contact_params"
        fields:
          - { label: "Email", name: "email", widget: "string" }
          - { label: "Phone", name: "phone", widget: "string" }
          - { label: "Phone link", name: "phone_link", widget: "string", pattern: ['^[0-9]*$', "Non valide"], hint: "Same as above but without spaces or special characters. Ex: 15143334444" }
          - { label: "Address", name: "address", widget: "string" }
          - { label: "Google Map link", name: "gmap_link", pattern: ['^https://goo.gl/maps/', "Doit débuter par : https://goo.gl/maps/"], widget: "string" }
      - file: "data/social_params.toml"
        label: "Réseaux Sociaux"
        name: "social_params"
        fields:
          - { label: "Facebook link", name: "facebook_link", widget: "string", required: false, hint: "Leave blank if none" }
          - { label: "Instagram link", name: "instagram_link", widget: "string", required: false, hint: "Leave blank if none" }
          - { label: "LinkedIn link", name: "linkedin_link", widget: "string", required: false, hint: "Leave blank if none" }
          - { label: "Twitter link", name: "twitter_link", widget: "string", required: false, hint: "Leave blank if none" }
          - { label: "Youtube link", name: "youtube_link", widget: "string", required: false, hint: "Leave blank if none" }
  