backend:
  name: git-gateway
  repo: wearebolean/hugo-decap-template
  branch: main

media_folder: "static/images" # Folder where user uploaded files should go
public_folder: "images"

i18n:
  structure: "multiple_files"
  locales:
    - "fr"
    - "en"

collections: 
  - label: Carrieres
    name: "carrieres"
    folder: "content/carrieres/list"
    create: true
    slug: "_{{slug}}/index"
    i18n: true
    editor:
      preview: false
    fields:
      - label: "Title"
        name: "title"
        hint: "Le nom unique du dossier qui contiendra toutes les infos ci-bas. Ex: nom-separer-par-des-traits"
        widget: "string"
      - label: "Affiché sur le site?"
        name: "type"
        widget: "select"
        i18n: duplicate
        options:
          - { label: "Oui", value: "visible" }
          - { label: "Non", value: "not_visible" }
      - label: "Sitemap"
        name: "sitemap"
        widget: "hidden"
        default: "true"
        i18n: duplicate
      - label: "Render as"
        name: "render_as"
        widget: "hidden"
        default: "cms-jobs"
        i18n: duplicate
      - label: "Content"
        name: "body"
        widget: "hidden"
        i18n: duplicate
        default: '{{< render-shared "carrieres/_introduction" >}}'
      - label: "Titre de l'emploi"
        name: "job_title"
        widget: "string"
        i18n: true
      - label: "Emplacement"
        name: "area"
        widget: "string"
        i18n: duplicate
      - label: "Ton quotidien"
        name: "quotidien"
        widget: "list"
        fields: 
          - {label: "Ajouter", name: "line", widget: "string"}
        i18n: true
      - label: "C’est l’emploi idéal pour toi si"
        name: "ideal"
        widget: "list"
        fields: 
          - {label: "Ajouter", name: "line", widget: "string"}
        i18n: true
      - label: "Ce que nous t’offrons"
        name: "offrons"
        widget: "list"
        fields: 
          - {label: "Ajouter", name: "line", widget: "string"}
        i18n: true
      - label: "Requis"
        name: "requis"
        widget: "list"
        fields: 
          - {label: "Ajouter", name: "line", widget: "string"}
        i18n: true
  - name: "pages"
    label: "Pages"
    folder: "content/pages"
    create: true
    i18n: true
    slug: "{{slug}}/index"
    fields:
      - {label: "Title", name: "title", widget: "string", i18n: duplicate}
      - {label: "Sections", name: "sections", widget: "list", i18n: duplicate, fields: [
          {label: "Section Type", name: "section_type", widget: "select", options: [
            {label: "Text Section", value: "text_section"},
            {label: "Image Section", value: "image_section"},
            {label: "Gallery Section", value: "gallery_section"},
            {label: "Hero Section", value: "hero_section"}
          ]},
          {label: "Section Content", name: "section_content", widget: "markdown", required: false, media_folder: "static/content", public_folder: "/content"},
          {label: "Image", name: "image", widget: "image", i18n: duplicate, required: false, media_folder: "static/images", public_folder: "/images"},
          {label: "Gallery Images", name: "gallery_images", i18n: duplicate, widget: "list", fields: [
            {label: "Image", name: "image", widget: "image", media_folder: "static/images", public_folder: "/images"}
          ]},
          {label: "Hero Image", name: "hero_image", widget: "image", i18n: duplicate, required: false, media_folder: "static/images", public_folder: "/images", default: "", conditional: [field: "sections.section_type", value: "hero_section"]},
          {label: "Hero Title", name: "hero_title", widget: "string", required: false, conditional: [field: "sections.section_type", value: "hero_section"]},
          {label: "Hero Subtitle", name: "hero_subtitle", widget: "string", required: false, conditional: [field: "sections.section_type", value: "hero_section"]}
        ]}
        #   {label: "Hero Image", name: "hero_image", widget: "image", i18n: duplicate, required: false, media_folder: "static/images", public_folder: "/images", default: "", if: "section_type == 'hero_section'"},
        #   {label: "Hero Title", name: "hero_title", widget: "string", required: false, if: "section_type == 'hero_section'"},
        #   {label: "Hero Subtitle", name: "hero_subtitle", widget: "string", required: false, if: "section_type == 'hero_section'"}
        # ]}

