backend:
  name: git-gateway
  repo: wearebolean/hugo-decap-template
  branch: main

media_folder: "static/img"
public_folder: "img"

i18n:
  structure: "multiple_files"
  locales:
    - "fr"
    - "en"

collections: 
  - name: "pages"
    label: "Pages"
    files:
      - file: "content/_index"
        label: "Home Page"
        name: "home"
        i18n: true
        fields:
          - {label: Title, name: title, widget: string}
          - {label: Subtitle, name: subtitle, widget: string}
          - {label: Image, name: image, widget: image}
          - {label: "Blurb", name: blurb, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Intro", name: intro, widget: object, fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Products", name: products, widget: list, fields: [
              {label: "Image", name: "image", widget: "image"},
              {label: "Text", name: "text", widget: "text"}]}
          - {label: "Values", name: "values", widget: "object", fields: [
              {label: "Heading", name: "heading", widget: string},
              {label: "Text", name: "text", widget: "text"}]}
      - file: "content/a-propos/_index"
        label: "À propos"
        name: "a-propos"
        i18n: true
        fields:
          - label: Nouvelle section
            name: section
            widget: list
            fields:
              - label: Section
                name: section_type
                widget: select
                options: 
                  - { label: "Hero", value: "hero_section", widget: "object", fields: 
                                                                        [{ - label: "Titre", name: "hero_title", widget: "string" }
                                                                        { - label: "Sous-titre", name: "hero_subtitle", widget: "string" }
                                                                        { - label: "Text", name: "hero_text", widget: "string" }]}
                    - { label: "Text", value: "text_section", widget: "object", fields: 
                                                                        [{ - label: "Titre_text", name: "hero_title", widget: "string" }
                                                                        { - label: "Sous-titre_text", name: "hero_subtitle", widget: "string" }
                                                                        { - label: "Text_text", name: "hero_text", widget: "string" }]}
